import 'package:flutter/material.dart';

const MAIN_COLOR_ALPHA = 0xFF70D799;
const MAIN_COLOR = 0x70D799;
const MAIN_COLOR_STRING = "#70D799";

const MAIN_COLOR_OBJECT = const Color(MAIN_COLOR_ALPHA);

const DARKER_MAIN_COLOR_ALPHA = 0xFF2ea45d;
const DARKER_MAIN_COLOR = 0x2ea45d;
const DARKER_MAIN_COLOR_STRING = "#2ea45d";

const DARKER_MAIN_COLOR_OBJECT = const Color(DARKER_MAIN_COLOR_ALPHA);

const LIGHTER_MAIN_COLOR_ALPHA = 0xFFade8c5;
const LIGHTER_MAIN_COLOR = 0xade8c5;
const LIGHTER_MAIN_COLOR_STRING = "#ade8c5";

const LIGHTER_MAIN_COLOR_OBJECT = const Color(LIGHTER_MAIN_COLOR_ALPHA);

const LIGHT_COLOR = 0xFFF3F3;
const LIGHT_COLOR_ALPHA = 0xFFFFF3F3;
const LIGHT_COLOR_STRING = "#FFF3F3";

const LIGHT_COLOR_OBJECT = const Color(LIGHT_COLOR_ALPHA);

const DARK_COLOR_ALPHA = 0xFF565656;
const DARK_COLOR = 0x565656;
const DARK_COLOR_STRING = "#565656";

const DARK_COLOR_OBJECT = const Color(DARK_COLOR_ALPHA);

const MARGIN_HOME_LAYOUT = 15.0;
const double RADIUS = 10;
